import{a as f,S as d,i as a}from"./assets/vendor-D1AWmRWP.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m="https://pixabay.com/api/",h="55674767-a2ab9f6f3f74198417133d166";function p(o=""){return f.get(m,{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data)}const l=document.querySelector(".gallery");let g=new d(".gallery a");function y(o){const r=o.map(({webformatURL:s,largeImageURL:n,tags:e,likes:t,views:i,comments:c,downloads:u})=>`
      <li class="gallery-item">
      <a href="${n}"><img class="img-item" src="${s}" alt="${e}" width="360" height="200"/></a>
      <div class="info">
  <p class="info-text">Likes:<br>${t}</p>
  <p class="info-text">Views:<br>${i}</p>
  <p class="info-text">Comments:<br>${c}</p>
  <p class="info-text">Downloads:<br>${u}</p>
  </div>
  </li> `).join("");l.insertAdjacentHTML("beforeend",r),g.refresh()}function L(){l.innerHTML=""}function b(){document.querySelector(".loader").classList.remove("hidden")}function w(){document.querySelector(".loader").classList.add("hidden")}const S=document.querySelector(".form");S.addEventListener("submit",v);function v(o){o.preventDefault();const r=o.target.elements["search-text"].value.toLowerCase().trim();if(!r){a.show({message:"Put value",color:"red",position:"bottomRight",overlayColor:"rgba(0, 0, 0, 0.6)"});return}L(),b(),p(r).then(s=>{if(s.hits.length===0){a.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"blue",position:"topCenter"});return}y(s.hits)}).catch(s=>{a.show({message:"Error! Try again later"}),console.log(s)}).finally(()=>{w(),o.target.reset()})}
//# sourceMappingURL=index.js.map
